#!/bin/sh
# Show all 16 terminal colors

printf "norm 0-7   "
for i in {0..7};do
   printf "\033[38;5;%dm███" "$i"
done
printf "\n           "
for i in {0..7};do
   printf "\033[38;5;%dm%3d" "$i" "$i"
done

printf "\n\033[0mbold 0-7   "
for i in {0..7};do
   printf "\033[38;5;%dm\033[1m███" "$i"
done
printf "\n           "
for i in {0..7};do
   printf "\033[38;5;%dm\033[1m%3d" "$i" "$i"
done

printf "\n"

printf "\n\033[0mnorm 8-15  "
for i in {0..7};do
   ((e = i + 8))
   printf "\033[38;5;%dm███" "$e"
done
printf "\n           "
for i in {0..7};do
   ((e = i + 8))
   printf "\033[38;5;%dm%3d" "$e" "$e"
done


printf "\n\033[0mbold 8-15  "
for i in {0..7};do
   ((e = i + 8))
   printf "\033[38;5;%dm\033[1m███" "$e"
done
printf "\n           "
for i in {0..7};do
   ((e = i + 8))
   printf "\033[38;5;%dm\033[1m%3d" "$e" "$e"
done


echo -e "\n"
