#!/bin/sh
# Uses the application name, and it's window class, and then figures out if
# it's open or not. If it is open, it focuses it (on i3). Otherwise, the
# application is run.

if [[ $# -ne 2 ]]; then
   echo "Invalid number of arguments. Takes 2. First is the application string, and the second is the application class."
   exit
fi

exists="$(i3-msg "[class=$2]" focus 2>/dev/null | jq '.[].success')"
echo "$exists"

if [[ "$exists" == 'false' ]]; then
   eval "$1"
fi
