#!/bin/sh
#
# Uses the application name, and it's window class, and then figures out if
# it's open or not. If it is open, it focuses it (on i3). Otherwise, the
# application is run.
#
# Dependencies:
# * jq

if [[ $# -ne 2 ]]; then
   echo "Invalid number of arguments. Takes 2. First is the application string, and the second is the application class."
   exit 1
fi

exists="$(i3-msg "[class=$2]" focus 2>/dev/null | jq '.[].success')"
if [[ "$exists" == 'false' ]]; then
   eval "$1" || { echo "Couldn't evaluate '$1' in i3_open_iff_noexist"; exit 1 ;}
fi
