#!/bin/sh

# Test notification system.

notify-send -u low "title" "body - urgency low 1"
notify-send -u normal "title" "body - urgency normal 2"
notify-send -u critical "title" "body - urgency critical 3"
