#!/bin/bash

function mainfunction () {
   exec 1>&-
   sshot $@
}


if [[ -z $@ ]]; then
   IFS=$'\n'
   disps=($(xrandr | grep " connected" | awk {'printf ("%s %s %s\n", $1,$3,$4)'}))
   echo "all"
   echo "selection"
   for i in ${!disps[@]}
   do
      printf "%s" ${disps[$i]} | awk {'printf ("%s\n", $1)'}
   done
   echo ""
   echo "-d 5 all"
   echo "-d 5 selection"
   for i in ${!disps[@]}
   do
      printf "%s" ${disps[$i]} | awk {'printf ("-d 5 %s\n", $1)'}
   done

else
   mainfunction $@
fi
