#!/bin/bash

# user variables


# application variables
## a nice way to add bindings
BIND1="alt+o"
BIND2="alt+p"

# launcher variables
MSG="Help text. $BIND1 does something, $BIND2 does something else."
PROMPT="template:"
ANSWER=""
SEL=""
FILTER=""
INDEX=0
if [[ -z "$LAUNCHER" ]];then
   LAUNCHER="rofi"
fi


# run correct launcher with prompt and help message
function _launcher () {
   rofi -dmenu -p "$PROMPT" -mesg "$MSG" \
      -kb-custom-1 "$BIND1" -kb-custom-2 "$BIND2" \
      -format 'i;f;s' -selected-row $INDEX -filter "$FILTER"
}

# function that creates a list for the launcher
function print_listofopts () {
   echo -e "a\\nb\\nbb\\nc" 
}

function main_function () {
   ANSWER=$(print_listofopts | _launcher)
   EXIT=$?
   #INDEX=${ANSWER%;*;*}
   #SEL=${ANSWER#*;*;}
   IFS=";" read -r INDEX FILTER SEL <<< "$ANSWER"
}

# Run the script
# Loop so that you can have submenus or toggle options
while true; do
   main_function
   echo "ANSWER: $ANSWER"
   echo "INDEX: $INDEX"
   echo "FILTER: $FILTER"
   echo "SEL: $SEL"
   echo "EXIT: $EXIT"
   if [[ $EXIT -eq 0 ]]; then
      # This is the case where enter is pressed.
      echo "Main function of the script"
      break
   elif [[ $EXIT -eq 1 ]]; then
      # This is the case where rofi es escaped (should EXIT)
      break
   elif [[ $EXIT -eq 10 ]]; then
      # What to do if -kb-custom-1 binding (BIND1) is pressed
      # remove if nothing should be done
      echo "$BIND1 was pressed!"
   elif [[ $EXIT -eq 11 ]]; then
      # What to do if -kb-custom-2 binding (BIND2) is pressed
      echo "$BIND2 was pressed!"
   else
      break
   fi
done
